"""OverviewCache table

Revision ID: 883ea54fc7a1
Revises: 5c3e9aaa4f7f
Create Date: 2024-09-27 19:54:46.560823

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "883ea54fc7a1"
down_revision = "5c3e9aaa4f7f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "overviewcache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaign.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("overviewcache")
    # ### end Alembic commands ###
