export const overviewData = {
  campaigns: [
    {
      id: "#3251",
      fileName: "Coffee explainer video ",
      createdOn: "22nd Jan s4",
      updatedOn: "22nd Jan 24",
      status: "Training in progress",
    },
    {
      id: "#3251",
      fileName: "Coffee explainer video ",
      createdOn: "22nd Jan s4",
      updatedOn: "22nd Jan 24",
      status: "Completed",
    },
    {
      id: "#3251",
      fileName: "Coffee explainer video ",
      createdOn: "22nd Jan s4",
      updatedOn: "22nd Jan 24",
      status: "Completed",
    },
    {
      id: "#3251",
      fileName: "Coffee explainer video ",
      createdOn: "22nd Jan s4",
      updatedOn: "22nd Jan 24",
      status: "Completed",
    },
    {
      id: "#3251",
      fileName: "Coffee explainer video ",
      createdOn: "22nd Jan s4",
      updatedOn: "22nd Jan 24",
      status: "Completed",
    },
    {
      id: "#3251",
      fileName: "Coffee explainer video ",
      createdOn: "22nd Jan s4",
      updatedOn: "22nd Jan 24",
      status: "Completed",
    },
    {
      id: "#3251",
      fileName: "Coffee explainer video ",
      createdOn: "22nd Jan s4",
      updatedOn: "22nd Jan 24",
      status: "Completed",
    },
    {
      id: "#3251",
      fileName: "Coffee explainer video ",
      createdOn: "22nd Jan s4",
      updatedOn: "22nd Jan 24",
      status: "Completed",
    },
    {
      id: "#3251",
      fileName: "Coffee explainer video ",
      createdOn: "22nd Jan s4",
      updatedOn: "22nd Jan 24",
      status: "Completed",
    },
    {
      id: "#3251",
      fileName: "Coffee explainer video ",
      createdOn: "22nd Jan s4",
      updatedOn: "22nd Jan 24",
      status: "Completed",
    },
    {
      id: "#3251",
      fileName: "Coffee explainer video ",
      createdOn: "22nd Jan s4",
      updatedOn: "22nd Jan 24",
      status: "Completed",
    },
    {
      id: "#3251",
      fileName: "Coffee explainer video ",
      createdOn: "22nd Jan s4",
      updatedOn: "22nd Jan 24",
      status: "Completed",
    },
    {
      id: "#3251",
      fileName: "Coffee explainer video ",
      createdOn: "22nd Jan s4",
      updatedOn: "22nd Jan 24",
      status: "Completed",
    },
    {
      id: "#3251",
      fileName: "Coffee explainer video ",
      createdOn: "22nd Jan s4",
      updatedOn: "22nd Jan 24",
      status: "Completed",
    },
  ],
  overviews: {
    totalPromoters: 3255,
    totalUserDetractors: 3255,
  },
};
