import { DotsHorizontal } from "../../assets/icons";

export const projectsTableColumns = [
  { id: "id", heading: "ID", value: (item) => item.id },
  { id: "fileName", heading: "File name", value: (item) => item.fileName },
  { id: "createOn", heading: "Create on", value: (item) => item.createdOn },
  { id: "updatedOn", heading: "Updated On", value: (item) => item.updatedOn },
  { id: "status", heading: "Status", value: (item) => item.status },
  { id: "actions", heading: "Actions", value: (item) => <DotsHorizontal /> },
];

export const projectsTableData = [
  {
    id: "#3251",
    fileName: "Coffee explainer video ",
    createdOn: "22nd Jan s4",
    updatedOn: "22nd Jan 24",
    status: "Completed",
  },
  {
    id: "#3251",
    fileName: "Coffee explainer video ",
    createdOn: "22nd Jan s4",
    updatedOn: "22nd Jan 24",
    status: "Completed",
  },
  {
    id: "#3251",
    fileName: "Coffee explainer video ",
    createdOn: "22nd Jan s4",
    updatedOn: "22nd Jan 24",
    status: "Completed",
  },
  {
    id: "#3251",
    fileName: "Coffee explainer video ",
    createdOn: "22nd Jan s4",
    updatedOn: "22nd Jan 24",
    status: "Completed",
  },
  {
    id: "#3251",
    fileName: "Coffee explainer video ",
    createdOn: "22nd Jan s4",
    updatedOn: "22nd Jan 24",
    status: "Completed",
  },
  {
    id: "#3251",
    fileName: "Coffee explainer video ",
    createdOn: "22nd Jan s4",
    updatedOn: "22nd Jan 24",
    status: "Completed",
  },
  {
    id: "#3251",
    fileName: "Coffee explainer video ",
    createdOn: "22nd Jan s4",
    updatedOn: "22nd Jan 24",
    status: "Completed",
  },
  {
    id: "#3251",
    fileName: "Coffee explainer video ",
    createdOn: "22nd Jan s4",
    updatedOn: "22nd Jan 24",
    status: "Completed",
  },
  {
    id: "#3251",
    fileName: "Coffee explainer video ",
    createdOn: "22nd Jan s4",
    updatedOn: "22nd Jan 24",
    status: "Completed",
  },
  {
    id: "#3251",
    fileName: "Coffee explainer video ",
    createdOn: "22nd Jan s4",
    updatedOn: "22nd Jan 24",
    status: "Completed",
  },
  {
    id: "#3251",
    fileName: "Coffee explainer video ",
    createdOn: "22nd Jan s4",
    updatedOn: "22nd Jan 24",
    status: "Completed",
  },
  {
    id: "#3251",
    fileName: "Coffee explainer video ",
    createdOn: "22nd Jan s4",
    updatedOn: "22nd Jan 24",
    status: "Completed",
  },
  {
    id: "#3251",
    fileName: "Coffee explainer video ",
    createdOn: "22nd Jan s4",
    updatedOn: "22nd Jan 24",
    status: "Completed",
  },
  {
    id: "#3251",
    fileName: "Coffee explainer video ",
    createdOn: "22nd Jan s4",
    updatedOn: "22nd Jan 24",
    status: "Completed",
  },
];